### PR TITLE
removes contributors: they are clearly seen in the commits themselves

### PR DESCRIPTION
**Pull request by xpepper**
Contributors are already visibile in the commits. Should we remove them?

### CODE REVIEW

**Comment by ivanlb** [comment]
I do agree 👍

**Comment by pdincau** [comment]
@xpepper @ivanlb I am not sure whether all the contributors are shown in the commits, but I see no issues in removing this part of the readme since this study plan was created by gathering feedback from all the XPeppers team.

For me you can merge the PR: what do you think @voxsim ?

**Comment by voxsim** [comment]
I agree

**Comment by xpepper** [comment]
Merged directly from the master

**Pull request closed without merging**
